name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  push:
    branches:
      - main

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v2
        with:
          repository: PokeRogue-Projects/Pathing-Tool
          ref: Automerge

      - name: Add upstream
        run: git remote add upstream https://github.com/pagefaultgames/pokerogue.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main
          git push origin Automerge
